#!/bin/busybox sh
/bin/busybox --install -s /bin

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

# get the wtux kernel argument if using for wanix to
# mount the host9p filesystem v86 may be providing
# and use ttyS0 for console
wtux=$(cat /proc/cmdline | awk '/wtux=/{split($0,a," "); for(i in a) if(a[i]~/^wtux=/) {sub(/^wtux=/,"",a[i]); print a[i]; exit}}')
console="tty1"
startdir="/"
if [ "$wtux" = "debug9p" ]; then
    mkdir -p /mnt/host9p
    mount -t 9p -o trans=virtio,cache=loose host9p /mnt/host9p
fi
if [ "$wtux" = "wanix" ]; then
    mkdir -p /wanix
    mount -t 9p -o trans=virtio,cache=loose host9p /wanix
    console="ttyS0"
    startdir="/wanix"
fi

# ip link set dev eth0 up
# ip addr add 10.0.2.15/24 dev eth0
# ip route add default via 10.0.2.2

# let kernel messages finish
sleep 1 

# start shell on $console with job control
setsid /bin/busybox sh -c "cd ${startdir} && exec /bin/busybox sh </dev/${console} >/dev/${console} 2>&1"